### ISSUE TITLE
Cannot access the full data set

### ISSUE THREAD

**Issue by kiriyama56** [deepmind/physical_concepts#1]
Hi, thank you for interesting paper and sharing the dataset.

I want to access to full of the dataset, but only part of it is accessible.
Specifically, I only have access to 100 train data, 10 test data and 20 probe quadruplets (instead of 300,000 train data, 5,000 test data and 5,000 quadruplets) from this link: https://console.cloud.google.com/storage/browser/physical_concepts 

Could you make the full dataset available?

**Comment by ElPiloto** [comment]
Thanks for your interest in the dataset.  The full dataset is in fact available.  I think this is a misunderstanding of how the `tfrecord` format works.  

Let's consider the test data.  The colab loads in **10** `tfrecord` files.  I believe this is why you think there are only **10** test data points.  But each `tfrecord` file for the test data contains 500 test data points.  500 * 100 = 5,000 test data points as described in the manuscript.  

You can verify this for yourself:
```
freeform_ds = make_freeform_tfrecord_dataset(is_train=False, shuffle=True)
count = 0
for test_data_point in freeform_ds.as_numpy_iterator():
  count += 1
print(f'Counted a total number of {count} test examples.')
# ----------------------Expected output:
# >>  Counted a total number of 5000 test examples.
```

Note that the number of data points per `tfrecord` file is different for the training data and also the probe quadruplets, but they all add up to the number of data points described in the manuscript.
